#Load packages
```{r}
library(httk)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(purrr)
library(readr)
library(forcats)
library(viridis)
library(Rtsne)
library(tibble)
library(showtext)
library(extrafont)
library(pracma)
library(ggrepel)

windowsFonts(Arial = windowsFont("Arial"))
```
#Validate httk
##Load PFAS information
```{r}
available_rblood2plasma(
  chem.cas = "1763-23-1",
    species = "Mouse",
    suppress.messages = TRUE,
  class.exclude = TRUE,
) 
available_rblood2plasma(
  chem.cas = "1763-23-1",
    species = "Human",
    suppress.messages = TRUE,
  class.exclude = TRUE,
)

get_caco2(
  chem.cas = "1763-23-1",
  suppress.messages = FALSE
)
available_rblood2plasma(
  chem.cas = "335-67-1",
    species = "Human",
    suppress.messages = TRUE,
  class.exclude = TRUE,
)
available_rblood2plasma(
  chem.cas = "335-67-1",
    species = "Mouse",
    suppress.messages = TRUE,
  class.exclude = TRUE,
)

get_caco2(
  chem.cas = "335-67-1",
  suppress.messages = FALSE
)
info_pfos_human <- subset(
  pfas.clearance,
  DTXSID == "DTXSID3031864" & Species == "Human"
)
info_pfos_human_avg <- info_pfos_human %>%
  dplyr::summarise(
    dplyr::across(where(is.numeric), ~ mean(.x, na.rm = TRUE))
  )
info_pfos_human_avg

info_pfoa_human <- subset(
  pfas.clearance,
  DTXSID == "DTXSID8031865" & Species == "Human"
)
info_pfoa_human_avg <- info_pfoa_human %>%
  dplyr::summarise(
    dplyr::across(where(is.numeric), ~ mean(.x, na.rm = TRUE))
  )
info_pfoa_human_avg


info_pfos_mouse <- subset(
  pfas.clearance,
  DTXSID == "DTXSID3031864" & Species == "Mouse"
)
info_pfos_mouse

info_pfoa_mouse <- subset(
  pfas.clearance,
  DTXSID == "DTXSID8031865" & Species == "Mouse"
)
info_pfoa_mouse

#account for cd1 to c57 conversion
pfoa_clearance_m <- 0.001331 *1.5 * 0.1805
pfoa_clearance_f <- 0.001851 *1.5 * 0.1805
```
##PFOS Plasma pfas1comp httk 2.7.2.
```{r}
# ---- Setup ----
shape_map <- c(`Male` = 24, `Female` = 21)
custom_colors_named <- c(
  "0"     = "#330597",
  "0.166" = "#b12a90",
  "0.5"   = "#d35171",
  "1"     = "#f68f44",
  "1.5"   = "#fec029"
)

# ---- Data Prep ----
pfos_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOS") %>%
  mutate(uM = as.numeric(trimws(uM)))

plasma_obs <- pfos_obs %>%
  filter(Tissue == "Plasma") %>%
  select(Dose, Time, uM, Mouse.ID, Sex)

dose_vec <- unique(pfos_obs$Dose)
time_vec <- unique(pfos_obs$Time)
sim_days <- max(time_vec)

# ---- Run PFAS model for both sexes ----
pred_1comp_all <- map_df(dose_vec, function(dose) {

  # ---- Female model ----
  pars_f <- parameterize_pfas1comp(
    chem.cas = "1763-23-1",
    species = "Mouse",
    dosingadj = "Oral",
    suppress.messages = TRUE
  )
  pars_f$Funbound.plasma <- 0.00256
  pars_f$Vdist <- 0.261
  pars_f$kelim <- 0.0008463
  pars_f$Rblood2plasma <- 0.588
  pars_f$Caco2.Pab <- 1.6

  sim_f <- solve_1comp(
    parameters    = pars_f,
    daily.dose    = dose,
    doses.per.day = 1,
    days          = sim_days,
    output.units  = "uM"
  )

  c_f <- if ("Cplasma" %in% colnames(sim_f)) sim_f[, "Cplasma"] else sim_f[, "Ccompartment"] / pars_f$Rblood2plasma
  pred_f <- approx(x = sim_f[, "time"], y = c_f, xout = time_vec, rule = 2)

  df_f <- tibble(
    Dose = dose,
    Time = pred_f$x,
    Predicted_Conc_uM = pred_f$y,
    Model = "PFAS-1comp Female"
  )

  # ---- Male model ----
  pars_m <- parameterize_pfas1comp(
    chem.cas = "1763-23-1",
    species = "Mouse",
    dosingadj = "Oral",
    suppress.messages = TRUE
  )
  pars_m$Funbound.plasma <-0.00256 #mouse c57 file:///C:/Users/aloan/Downloads/toxics-12-00253.pdf
  pars_m$Vdist <- 0.263
  pars_m$kelim <- 0.0007290 
  pars_m$Rblood2plasma <- 0.588
  pars_m$Caco2.Pab <- 1.6
  
  pars <- rbind(pars_f, pars_m)
write.csv(pars, "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/PBTK-Modelling-PFAS/Output/pars_pfos_1comp.csv")
  sim_m <- solve_1comp(
    parameters    = pars_m,
    daily.dose    = dose,
    doses.per.day = 1,
    days          = sim_days,
    output.units  = "uM"
  )

  c_m <- if ("Cplasma" %in% colnames(sim_m)) sim_m[, "Cplasma"] else sim_m[, "Ccompartment"] / pars_m$Rblood2plasma
  pred_m <- approx(x = sim_m[, "time"], y = c_m, xout = time_vec, rule = 2)

  df_m <- tibble(
    Dose = dose,
    Time = pred_m$x,
    Predicted_Conc_uM = pred_m$y,
    Model = "PFAS-1comp Male"
  )

  bind_rows(df_f, df_m)
})

# ---- Combine Dose-Time ----
plasma_obs$Dose_Time <- paste0(plasma_obs$Dose, " (", plasma_obs$Time, ")")
pred_1comp_all$Dose_Time <- paste0(pred_1comp_all$Dose, " (", pred_1comp_all$Time, ")")
pred_1comp_all <- subset(pred_1comp_all, !(Dose_Time %in% c("0.166 (28)", "0.5 (28)", "1 (28)")))
# ---- Plot ----
p <- ggplot() +
  geom_jitter(
    data = plasma_obs,
    aes(x = factor(Dose_Time), y = uM, color = factor(Dose), fill = factor(Dose), shape = Sex),
    size = 2, alpha = 0.5, width = 0.1, stroke = 1
  ) +
  geom_point(
    data = pred_1comp_all,
    aes(x = factor(Dose_Time), y = Predicted_Conc_uM, color = Model, shape = Model),
    size = 2
  ) +
  labs(
    title = "PFOS — Plasma: PFAS 1-comp vs Observed",
    x = "Dose (mg/kg/day)",
    y = "Plasma (µM)",
    color = "Dose / Model"
  ) +
  scale_color_manual(
    values = c(custom_colors_named, "PFAS-1comp Female" = "red", "PFAS-1comp Male" = "red")
  ) +
  scale_fill_manual(values = custom_colors_named) +
  scale_shape_manual(
    values = c(shape_map, "PFAS-1comp Female" = 16, "PFAS-1comp Male" = 17)
  ) +
  theme_minimal() +
  coord_cartesian(ylim = c(-10, 800)) +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "b",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  )

print(p)
ggsave(filename = "../plots/pfos_1comp.png", plot = p, width = 6, height = 3, dpi = 300,bg = "white")


obs_vs_pred_table <- plasma_obs %>%
  inner_join(pred_1comp_all, by = "Dose_Time", "Sex") %>%
  mutate(
    diff_uM   = Predicted_Conc_uM - uM,        # absolute difference
    fold_diff = Predicted_Conc_uM / uM,        # fold-change
    percent_diff = 100 * diff_uM / uM          # % difference
  ) %>%
  select(
    Dose_Time,
    Sex,
    Observed_uM  = uM,
    Predicted_uM = Predicted_Conc_uM,
    diff_uM,
    fold_diff,
    percent_diff
  ) %>%
  arrange(desc(fold_diff))


obs_vs_pred_table %>%
summarise(
    n = n(),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_fold  = mean(fold_diff, na.rm = TRUE),
    times_lower = ifelse(mean_fold < 1, 1 / mean_fold, NA_real_),
    times_higher = ifelse(mean_fold > 1, mean_fold, NA_real_),
    .groups = "drop"
  )
pred_1comp_avg <- pred_1comp_all %>%
  group_by(Dose, Time) %>%
  summarise(
    Predicted_Conc_uM = mean(Predicted_Conc_uM, na.rm = TRUE),
    .groups = "drop"
  )
replicate_summary <- plasma_obs%>%
  group_by(Dose, Time) %>%  
  summarise(n = n(), .groups = "drop")
min_n <- min(replicate_summary$n)
max_n <- max(replicate_summary$n)
cat(sprintf("n = %d–%d mice/group\n", min_n, max_n))
```

##PFOA Plasma pfas1comp httk 2.7.2.
```{r}

available_rblood2plasma(
  chem.cas = "335-67-1",
    species = "Mouse",
    suppress.messages = TRUE,
  class.exclude = TRUE,
)

# ---- Data Prep ----
pfoa_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOA") %>%
  mutate(uM = as.numeric(trimws(uM)))

plasma_obs <- pfoa_obs %>%
  filter(Tissue == "Plasma") %>%
  select(Dose, Time, uM, Mouse.ID, Sex)

dose_vec <- unique(pfoa_obs$Dose)
time_vec <- unique(pfoa_obs$Time)
sim_days <- max(time_vec)

# ---- Run PFAS model for both sexes ----
pred_1comp_all <- map_df(dose_vec, function(dose) {

  # ---- Female model ----
  pars_f <- parameterize_pfas1comp(
    chem.cas = "335-67-1",
    species = "Mouse",
    dosingadj = "Oral",
    suppress.messages = TRUE
  )
  pars_f$Funbound.plasma <-  0.0142 #mouse c57 file:///C:/Users/aloan/Downloads/toxics-12-00253.pdf
  pars_f$Vdist <- 0.1805
  pars_f$kelim <- 0.001851 * 1.5 #https://pmc.ncbi.nlm.nih.gov/articles/PMC4464984/
  pars_f$Rblood2plasma <- 0.9047 # from r2bp function
  pars_f$Caco2.Pab <- 1.6

  sim_f <- solve_1comp(
    parameters    = pars_f,
    daily.dose    = dose,
    doses.per.day = 1,
    days          = sim_days,
    output.units  = "uM"
  )

  c_f <- if ("Cplasma" %in% colnames(sim_f)) sim_f[, "Cplasma"] else sim_f[, "Ccompartment"] / pars_f$Rblood2plasma
  pred_f <- approx(x = sim_f[, "time"], y = c_f, xout = time_vec, rule = 2)

  df_f <- tibble(
    Dose = dose,
    Time = pred_f$x,
    Predicted_Conc_uM = pred_f$y,
    Model = "PFAS-1comp Female"
  )

  # ---- Male model ----
  pars_m <- parameterize_pfas1comp(
    chem.cas = "335-67-1",
    species = "Mouse",
    dosingadj = "Oral",
    suppress.messages = TRUE
  )
  pars_m$Funbound.plasma <- 0.0142 #mouse c57 file:///C:/Users/aloan/Downloads/toxics-12-00253.pdf
  pars_m$Vdist <- 0.1805
  pars_m$kelim <- 0.001331* 1.5 #https://pmc.ncbi.nlm.nih.gov/articles/PMC4464984/
  pars_m$Rblood2plasma <- 0.9047 # from r2bp function
  pars_m$Caco2.Pab <- 1.6
  pars <- rbind(pars_f, pars_m)
write.csv(pars, "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/PBTK-Modelling-PFAS/Output/pars_pfoa_1comp.csv")
  sim_m <- solve_1comp(
    parameters    = pars_m,
    daily.dose    = dose,
    doses.per.day = 1,
    days          = sim_days,
    output.units  = "uM"
  )

  c_m <- if ("Cplasma" %in% colnames(sim_m)) sim_m[, "Cplasma"] else sim_m[, "Ccompartment"] / pars_m$Rblood2plasma
  pred_m <- approx(x = sim_m[, "time"], y = c_m, xout = time_vec, rule = 2)

  df_m <- tibble(
    Dose = dose,
    Time = pred_m$x,
    Predicted_Conc_uM = pred_m$y,
    Model = "PFAS-1comp Male"
  )

  bind_rows(df_f, df_m)
})

# ---- Combine Dose-Time ----
plasma_obs$Dose_Time <- paste0(plasma_obs$Dose, " (", plasma_obs$Time, ")")
pred_1comp_all$Dose_Time <- paste0(pred_1comp_all$Dose, " (", pred_1comp_all$Time, ")")
pred_1comp_all <- subset(pred_1comp_all, !(Dose_Time %in% c("0.166 (28)", "0.5 (28)", "1 (28)")))
# ---- Plot ----
p <- ggplot() +
  geom_jitter(
    data = plasma_obs,
    aes(x = factor(Dose_Time), y = uM, color = factor(Dose), fill = factor(Dose), shape = Sex),
    size = 2, alpha = 0.5, width = 0.1, stroke = 1
  ) +
  geom_point(
    data = pred_1comp_all,
    aes(x = factor(Dose_Time), y = Predicted_Conc_uM, color = Model, shape = Model),
    size = 2
  ) +
  labs(
    title = "PFOA — Plasma: PFAS 1-comp vs Observed",
    x = "Dose (mg/kg/day)",
    y = "Plasma (µM)",
    color = "Dose / Model"
  ) +
  scale_color_manual(
    values = c(custom_colors_named, "PFAS-1comp Female" = "red", "PFAS-1comp Male" = "red")
  ) +
  scale_fill_manual(values = custom_colors_named) +
  scale_shape_manual(
    values = c(shape_map, "PFAS-1comp Female" = 16, "PFAS-1comp Male" = 17)
  ) +
  theme_minimal() +
  coord_cartesian(ylim = c(-10, 800)) +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "b",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  )


print(p)
ggsave(filename = "../plots/pfoa_1comp.png", plot = p, width = 6, height = 3, dpi = 300,bg = "white")


obs_vs_pred_table <- plasma_obs %>%
  inner_join(pred_1comp_all, by = "Dose_Time") %>%
  mutate(
    diff_uM   = Predicted_Conc_uM - uM,        # absolute difference
    fold_diff = Predicted_Conc_uM / uM,        # fold-change
    percent_diff = 100 * diff_uM / uM          # % difference
  ) %>%
  select(
    Dose_Time,
    Sex,
    Observed_uM  = uM,
    Predicted_uM = Predicted_Conc_uM,
    diff_uM,
    fold_diff,
    percent_diff
  ) %>%
  arrange(desc(fold_diff))


obs_vs_pred_table %>%
summarise(
    n = n(),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_fold  = mean(fold_diff, na.rm = TRUE),
    times_lower = ifelse(mean_fold < 1, 1 / mean_fold, NA_real_),
    times_higher = ifelse(mean_fold > 1, mean_fold, NA_real_),
    .groups = "drop"
  )
pred_1comp_avg <- pred_1comp_all %>%
  group_by(Dose, Time) %>%
  summarise(
    Predicted_Conc_uM = mean(Predicted_Conc_uM, na.rm = TRUE),
    .groups = "drop"
  )
replicate_summary <- plasma_obs%>%
  group_by(Dose, Time) %>%  
  summarise(n = n(), .groups = "drop")
min_n <- min(replicate_summary$n)
max_n <- max(replicate_summary$n)
cat(sprintf("n = %d–%d mice/group\n", min_n, max_n))
```

# Calculate kliver2pu
```{r}
fu_values <- c(
  PFOA = 0.0142,
  PFOS = 0.00256
)
df_filtered <- pfas_obs_all %>%
  filter(Tissue %in% c("Plasma", "Liver"))
df_wide <- df_filtered %>%
  select(Mouse.ID, Sex, PFAS_type, Dose, Time, Tissue, mg_L, mg_kg) %>%
  filter(Dose != 0) %>%
  pivot_wider(
    names_from = Tissue,
    values_from = c(mg_L, mg_kg)
  )
df_wide <- df_wide %>%
  mutate(
    fu_plasma = fu_values[PFAS_type],
    Kliver2pu = mg_kg_Liver / (fu_plasma * mg_L_Plasma),
    #Kkidney2pu = mg_kg_Kidney / (fu_plasma * mg_L_Plasma),
    Liver_Plasma_Ratio = mg_kg_Liver / mg_L_Plasma,
   # Kidney_Plasma_Ratio = mg_kg_Kidney / mg_L_Plasma
  )
K2pu <- df_wide %>%
  group_by(PFAS_type, Sex) %>%
  summarise(
    mean_Kliver2pu = mean(Kliver2pu, na.rm = TRUE),
    mean_Liver_Plasma_Ratio = mean(Liver_Plasma_Ratio, na.rm = TRUE),
    n = n()
  )



```

###PFOS Plasma PBTK solve_pbtk (class.exclude =F)
```{r}
shape_map <- c(`Male` = 24, `Female` = 21)
pfos_obs <- pfas_obs_all %>%
  filter(
    PFAS_type == "PFOS",
    Tissue != "Feces"
  )

dose_vec <- unique(pfos_obs$Dose)
time_vec <- unique(pfos_obs$Time)
sim_days <- max(time_vec)
tissues_all <- c("Plasma", "Liver", "Kidney", "Lung", "Gut", "Rest")

# Function to map tissue names to PBTK model column names
tissue_to_col <- function(tissue) {
  switch(tissue,
         Plasma = "Cplasma",
         Liver = "Cliver",
         Kidney = "Ckidney",
         Lung = "Clung",
         Gut = "Cgut",
         Rest = "Crest")
}

# Base parameterization (run once)
pars_base <- parameterize_pbtk(
  chem.cas = "1763-23-1",
  species = "Mouse",
  dosingadj = "Oral",
  class.exclude = FALSE,
  suppress.messages = TRUE,
  default.to.human = TRUE
)

# ---- Male parameters ----
pars_m <- pars_base
pars_m$Vdist <- 0.263
pars_m$kelim <- 0.0007290
pars_m$Funbound.plasma <- 0.00256
pars_m$Rblood2plasma <- 0.588
pars_m$Caco2.Pab <- 1.6
pars_m$Clmetabolismc <- 0.0001917
pars_m$Fabsgut <- 0.9798 #https://www.ncbi.nlm.nih.gov/books/NBK614278/
pars_m$kgutabs <- 1.572
pars_m$Kliver2pu <- 1344.4930 

# ---- Female parameters ----
pars_f <- pars_base
pars_f$Vdist <- 0.261
pars_f$kelim <- 0.0008463
pars_f$Funbound.plasma <- 0.00256
pars_f$Rblood2plasma <- 0.588
pars_f$Caco2.Pab <- 1.6
pars_f$Clmetabolismc <- 0.0002209
pars_f$Fabsgut <- 0.9798 #https://www.ncbi.nlm.nih.gov/books/NBK614278/
pars_f$kgutabs <- 1.572
pars_f$Kliver2pu <- 846.4236

pars_f_df <- data.frame(
  Parameter = names(pars_f),
  Female = unlist(pars_f)
)

pars_m_df <- data.frame(
  Parameter = names(pars_m),
  Male = unlist(pars_m)
)

pars <- full_join(pars_f_df, pars_m_df, by = "Parameter")

# Write both parameter sets
write.csv(pars, "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/PBTK-Modelling-PFAS/Output/pars_pfos_pbtk.csv")


# Run model and get predictions
predictions <- map_df(dose_vec, function(dose) {

  map_df(c("Male", "Female"), function(sex) {

    pars <- if (sex == "Male") pars_m else pars_f

    out <- solve_pbtk(
      chem.cas = "1763-23-1",
      days = max(time_vec),
      doses.per.day = 1,
      daily.dose = dose,
      output.units = "uM",
      parameters = pars
    )

    map_df(tissues_all, function(tiss) {

      col_name <- tissue_to_col(tiss)
      if (!(col_name %in% colnames(out))) return(NULL)

      pred <- approx(
        x = out[, "time"],
        y = out[, col_name],
        xout = time_vec,
        rule = 2
      )

      tibble(
        Dose = dose,
        Time = pred$x,
        Tissue = tiss,
        Sex = sex,
        Predicted_Conc_uM = pred$y
      )
    })
  })
})
solve_pbtk
# Join model predictions with observed data 
comparison <- pfos_obs %>%
  left_join(predictions, by = c("Dose", "Time", "Tissue"))

# Separate predicted-only data for tissues without observations
model_only <- predictions %>%
  anti_join(pfos_obs, by = c("Dose", "Time", "Tissue"))

pfos_obs <- pfos_obs %>%
  mutate(uM = as.numeric(trimws(uM)),
        Tissue = factor(Tissue, levels = tissues_all)) 

predictions <- predictions %>%
  mutate(
    Tissue = factor(Tissue, levels = tissues_all))

pfos_obs$Dose_Time <- paste0(pfos_obs$Dose, " (", pfos_obs$Time, ")")
predictions$Dose_Time <- paste0(predictions$Dose, " (", predictions$Time, ")")
predictions <- subset(predictions, !(Dose_Time %in% c("0.166 (28)", "0.5 (28)", "1 (28)")))


plot_pfos <- ggplot() +
    # ---- Observed (dose-colored) ----
  geom_jitter(
    data = pfos_obs %>% filter(Time %in% c(28, 56)),
    aes(x = factor(Dose_Time), y = uM, shape = factor(Sex), color = factor(Dose), fill = factor(Dose)),
    size = 2, alpha = 0.5, width = 0.1, stroke = 1,
  ) +
  geom_point(
    data = predictions %>% filter(Time %in% c(28, 56)),
    aes( x =factor(Dose_Time), y = Predicted_Conc_uM, shape = Sex),
    fill = "red",color = "red", size = 2, 
  ) +
  facet_wrap(~ Tissue, scales = "free_y") +
  scale_color_manual(
    name = "Color",
    values = c(custom_colors_named)
  ) +
  scale_fill_manual(
    name = "Dose",
    values = custom_colors_named
  ) +
  scale_shape_manual(
    name = "Sex",
    values = shape_map
  ) +
  labs(
    title = "Predicted vs Observed PFOS Concentrations (PBTK)",
    x = "Dose (mg/kg)",
    y = "PFOS Concentration (µM)"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank())

print(plot_pfos)

ggsave(filename = "../plots/pfos_pbtk.png", plot = plot_pfos, width = 12.5, height = 7.5, dpi = 300,bg = "white")


predictions <- subset(predictions, Tissue %in% c("Plasma", "Liver")) #add kidney later

obs_vs_pred_table <- pfos_obs %>%
  inner_join(
    predictions,
    by = c("Dose_Time", "Tissue", "Sex")
  ) %>%
  mutate(
    diff_uM      = Predicted_Conc_uM - uM,
    fold_diff    = Predicted_Conc_uM / uM,
    percent_diff = 100 * diff_uM / uM
  ) %>%
  select(
    Dose_Time,
    Tissue,
    Sex,
    Observed_uM  = uM,
    Predicted_uM = Predicted_Conc_uM,
    diff_uM,
    fold_diff,
    percent_diff
  ) %>%
  arrange(Tissue, desc(fold_diff))


tissue_summary <- obs_vs_pred_table %>%
  group_by(Tissue) %>%
  summarise(
    n = n(),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_fold  = mean(fold_diff, na.rm = TRUE),
    times_lower = ifelse(mean_fold < 1, 1 / mean_fold, NA_real_),
    times_higher = ifelse(mean_fold > 1, mean_fold, NA_real_),
    .groups = "drop"
  )

tissue_summary
replicate_summary <- pfos_obs%>%
  group_by(Dose, Time, Tissue) %>%  
  summarise(n = n(), .groups = "drop")
min_n <- min(replicate_summary$n)
max_n <- max(replicate_summary$n)
cat(sprintf("n = %d–%d mice/group\n", min_n, max_n))
```

###PFOA Plasma PBTK solve_pbtk (class.exclude =F)
```{r}
shape_map <- c(`Male` = 24, `Female` = 21)
pfoa_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOA",
    Tissue != "Feces")

dose_vec <- unique(pfoa_obs$Dose)
time_vec <- unique(pfoa_obs$Time)
sim_days <- max(time_vec)
tissues_all <- c("Plasma", "Liver", "Kidney", "Lung", "Gut", "Rest")

# Function to map tissue names to PBTK model column names
tissue_to_col <- function(tissue) {
  switch(tissue,
         Plasma = "Cplasma",
         Liver = "Cliver",
         Kidney = "Ckidney",
         Lung = "Clung",
         Gut = "Cgut",
         Rest = "Crest")
}
# Base parameterization (run once)
pars_base <- parameterize_pbtk(
  chem.cas = "335-67-1",
  species = "Mouse",
  dosingadj = "Oral",
  class.exclude = FALSE,
  suppress.messages = TRUE,
  default.to.human = TRUE
)

# ---- Male parameters ----
pars_m <- pars_base
pars_m$Vdist <- 0.1805
pars_m$kelim <- 0.001331 * 1.5 #https://pmc.ncbi.nlm.nih.gov/articles/PMC4464984/
pars_m$Funbound.plasma <- 0.0142
pars_m$Rblood2plasma <- 0.9047
pars_m$Caco2.Pab <- 1.6
pars_m$Clmetabolismc <- pfoa_clearance_m
pars_m$Fabsgut <- 0.9798 #https://www.ncbi.nlm.nih.gov/books/NBK614278/
pars_m$kgutabs <- 1.572
pars_m$Kliver2pu <- 179.3938
  
# ---- Female parameters ----
pars_f <- pars_base
pars_f$Vdist <- 0.1805
pars_f$kelim <- 0.001851 * 1.5 #https://pmc.ncbi.nlm.nih.gov/articles/PMC4464984/
pars_f$Funbound.plasma <- 0.0142
pars_f$Rblood2plasma <- 0.9047
pars_f$Caco2.Pab <- 1.6
pars_f$Clmetabolismc <- pfoa_clearance_f
pars_f$Fabsgut <- 0.9798 #https://www.ncbi.nlm.nih.gov/books/NBK614278/
pars_f$kgutabs <- 1.572
pars_f$Kliver2pu <- 130.5985

pars_f_df <- data.frame(
  Parameter = names(pars_f),
  Female = unlist(pars_f)
)

pars_m_df <- data.frame(
  Parameter = names(pars_m),
  Male = unlist(pars_m)
)

pars <- full_join(pars_f_df, pars_m_df, by = "Parameter")

# Write both parameter sets
write.csv(pars, "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/PBTK-Modelling-PFAS/Output/pars_pfoa_pbtk.csv")

# Run model and get predictions
predictions <- map_df(dose_vec, function(dose) {

  map_df(c("Male", "Female"), function(sex) {

    pars <- if (sex == "Male") pars_m else pars_f

    out <- solve_pbtk(
      chem.cas = "335-67-1",
      days = max(time_vec),
      doses.per.day = 1,
      daily.dose = dose,
      output.units = "uM",
      parameters = pars
    )

    map_df(tissues_all, function(tiss) {

      col_name <- tissue_to_col(tiss)
      if (!(col_name %in% colnames(out))) return(NULL)

      pred <- approx(
        x = out[, "time"],
        y = out[, col_name],
        xout = time_vec,
        rule = 2
      )

      tibble(
        Dose = dose,
        Time = pred$x,
        Tissue = tiss,
        Sex = sex,
        Predicted_Conc_uM = pred$y
      )
    })
  })
})

# Join model predictions with observed data 
comparison <- pfoa_obs %>%
  left_join(predictions, by = c("Dose", "Time", "Tissue"))

# Separate predicted-only data for tissues without observations
model_only <- predictions %>%
  anti_join(pfoa_obs, by = c("Dose", "Time", "Tissue"))

pfoa_obs <- pfoa_obs %>%
    mutate(uM = as.numeric(trimws(uM)),
    Tissue = factor(Tissue, levels = tissues_all)) 

predictions <- predictions %>%
  mutate(
    Tissue = factor(Tissue, levels = tissues_all))


pfoa_obs$Dose_Time <- paste0(pfoa_obs$Dose, " (", pfoa_obs$Time, ")")
predictions$Dose_Time <- paste0(predictions$Dose, " (", predictions$Time, ")")
predictions <- subset(predictions, !(Dose_Time %in% c("0.166 (28)", "0.5 (28)", "1 (28)")))

plot_pfoa <- ggplot() +
    # ---- Observed (dose-colored) ----
  geom_jitter(
    data = pfoa_obs %>% filter(Time %in% c(28, 56)),
    aes(x = factor(Dose_Time), y = uM, shape = factor(Sex), color = factor(Dose), fill = factor(Dose)),
    size = 2, alpha = 0.5, width = 0.1, stroke = 1, 
  ) +
  geom_point(
    data = predictions %>% filter(Time %in% c(28, 56)),
    aes(x = factor(Dose_Time), y = Predicted_Conc_uM, shape = Sex),
    fill = "red",color = "red", size = 2, 
  ) +
  facet_wrap(~ Tissue, scales = "free_y") +
  scale_color_manual(
    name = "Color",
    values = c(custom_colors_named)
  ) +
  scale_fill_manual(
    name = "Dose",
    values = custom_colors_named
  ) +
  scale_shape_manual(
    name = "Sex",
    values = shape_map
  ) +
  labs(
    title = "Predicted vs Observed PFOS Concentrations (PBTK)",
    x = "Dose (mg/kg)",
    y = "PFOA Concentration (µM)"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank())

print(plot_pfoa)

ggsave(filename = "../plots/pfoa_pbtk.png", plot = plot_pfoa, width = 12.5, height = 7.5, dpi = 300,bg = "white")

obs_vs_pred_table <- pfoa_obs %>%
  inner_join(
    predictions,
    by = c("Dose_Time", "Tissue", "Sex")
  ) %>%
  mutate(
    diff_uM      = Predicted_Conc_uM - uM,
    fold_diff    = Predicted_Conc_uM / uM,
    percent_diff = 100 * diff_uM / uM
  ) %>%
  select(
    Dose_Time,
    Tissue,
    Sex,
    Observed_uM  = uM,
    Predicted_uM = Predicted_Conc_uM,
    diff_uM,
    fold_diff,
    percent_diff
  ) %>%
  arrange(Tissue, desc(fold_diff))


tissue_summary <- obs_vs_pred_table %>%
  group_by(Tissue) %>%
  summarise(
    n = n(),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_diff_uM = mean(diff_uM, na.rm = TRUE),
    mean_fold  = mean(fold_diff, na.rm = TRUE),
    times_lower = ifelse(mean_fold < 1, 1 / mean_fold, NA_real_),
    times_higher = ifelse(mean_fold > 1, mean_fold, NA_real_),
    .groups = "drop"
  )
tissue_summary

replicate_summary <- pfoa_obs%>%
  group_by(Dose, Time, Tissue) %>%  
  summarise(n = n(), .groups = "drop")
min_n <- min(replicate_summary$n)
max_n <- max(replicate_summary$n)
cat(sprintf("n = %d–%d mice/group\n", min_n, max_n))
```

##PFOS Clearance 
```{r}
shape_map <- c(`Male` = 24, `Female` = 21)

#convert to ml/day/kg
clearance_pred_m <- 0.0002063 * 24* 1000
clearance_pred_f <- 0.0002209 * 24* 1000

clearance <- mean(c(clearance_pred_f, clearance_pred_m), na.rm = TRUE)

  
pfos_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOS")

fecal_obs <- pfos_obs %>%
  filter(Tissue == "Feces") %>% 
   filter(Group != "Vehicle") %>%
  select(Dose, Time, PFAS_conc, Mouse.ID, Sex) %>%
  mutate(
    # Convert ng/g → ng/kg feces
    ng_kg_feces = PFAS_conc * 1000,

    # Fecal excretion rate (kg feces / h / kg bw)
    feces_rate_kg_h_kg = 0.08 / 24,

    # Final excretion rate: ng / h / kg bw
    ng_h_kg = ng_kg_feces * feces_rate_kg_h_kg
  ) %>%
  group_by(Dose, Time)

plasma_obs <- pfos_obs %>%
  filter(Tissue == "Plasma") %>%
  select(Dose, Time, ng_L, Mouse.ID, Sex)

clearance_fecal <- fecal_obs %>%
  left_join(plasma_obs, by = c("Mouse.ID", "Dose", "Time", "Sex")) %>%
  mutate(
    CL_L_h_kg = ng_h_kg / ng_L)

#Convert L/h/kg → mL/day/kg

clearance_fecal <- clearance_fecal %>%
  mutate(
    CL_ml_day_kg = CL_L_h_kg * 24 * 1000)

clearance_fecal$Dose_Time <- paste0(clearance_fecal$Dose, " (", clearance_fecal$Time, ")")


p <- ggplot() +
    geom_jitter(
    data = clearance_fecal,
    aes(x = factor(Dose_Time), y = CL_ml_day_kg, color = factor(Dose), fill = factor(Dose), shape = factor(Sex)),
    size = 2, alpha = 0.5, width = 0.1, stroke = 1 
    ) +
  labs(
    title = "PFOS —Clearance"
  ) +
    geom_hline(yintercept = clearance_pred_f, linetype = "dashed", color = "red", linewidth =0.8) +
  geom_hline(yintercept = clearance_pred_m, linetype = "dashed", color = "blue", linewidth =0.8) +
  scale_color_manual(
  name = "Color",
  values = c(custom_colors_named)
  ) +
  scale_fill_manual(
  name = "Dose",
  values = custom_colors_named
  ) +
  scale_shape_manual(
  name = "Sex",
  values = shape_map
  ) +
  theme_minimal() +
 coord_cartesian(ylim = c(0, 12.5)) + 
  theme(
      text = element_text(family = "Arial", size = 12),
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "b",
      panel.grid.major = element_line(size = 0.5),
      panel.grid.minor = element_blank())
print(p)
ggsave(filename = "../plots/pfos_clerance.png", plot = p, width = 6, height = 3, dpi = 300,bg = "white")

mean <- clearance_fecal %>%
  ungroup() %>%
  summarise(
    n = n(),
    mean_CL_ml_day_kg = mean(CL_ml_day_kg, na.rm = TRUE)
  )
FC <- clearance/mean$mean_CL_ml_day_kg

replicate_summary <- clearance_fecal%>%
  group_by(Dose, Time) %>%  
  summarise(n = n(), .groups = "drop")
min_n <- min(replicate_summary$n)
max_n <- max(replicate_summary$n)
cat(sprintf("n = %d–%d mice/group\n", min_n, max_n))
```
##PFOA Clearance
```{r}
#convert to ml/day/kg
clearance_pred_m <- pfoa_clearance_m * 24* 1000
clearance_pred_f <- pfoa_clearance_f * 24* 1000
clearance <- mean(c(clearance_pred_f, clearance_pred_m), na.rm = TRUE)


pfoa_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOA")

fecal_obs <- pfoa_obs %>%
  filter(Tissue == "Feces") %>% 
  filter(Group != "Vehicle") %>% 
  select(Dose, Time, PFAS_conc, Mouse.ID, Sex) %>%
  mutate(
    # Convert ng/g → ng/kg feces
    ng_kg_feces = PFAS_conc * 1000,

    # Fecal excretion rate (kg feces / h / kg bw)
    feces_rate_kg_h_kg = 0.08 / 24,

    # Final excretion rate: ng / h / kg bw
    ng_h_kg = ng_kg_feces * feces_rate_kg_h_kg
  ) %>%
  group_by(Dose, Time)

plasma_obs <- pfoa_obs %>%
  filter(Tissue == "Plasma") %>%
  select(Dose, Time, ng_L, Mouse.ID, Sex)

clearance_fecal <- fecal_obs %>%
  left_join(plasma_obs, by = c("Mouse.ID", "Dose", "Time", "Sex")) %>%
  mutate(
    CL_L_h_kg = ng_h_kg / ng_L)


#Convert L/h/kg → mL/day/kg

clearance_fecal <- clearance_fecal %>%
  mutate(
    CL_ml_day_kg = CL_L_h_kg * 24 * 1000)
clearance_fecal$Dose_Time <- paste0(clearance_fecal$Dose, " (", clearance_fecal$Time, ")")

p <- ggplot() +
    geom_jitter(
    data = clearance_fecal,
    aes(x = factor(Dose_Time), y = CL_ml_day_kg, color = factor(Dose), fill = factor(Dose), shape = factor(Sex)),
    size = 2, alpha = 0.5, width = 0.1, stroke = 1 
    ) +
    labs(
    title = "PFOA —Clearance"
  ) +
  geom_hline(yintercept = clearance_pred_f, linetype = "dashed", color = "red", linewidth =0.8) +
  geom_hline(yintercept = clearance_pred_m, linetype = "dashed", color = "blue", linewidth =0.8) +
  scale_color_manual(
  name = "Color",
  values = c(custom_colors_named)
  ) +
  scale_fill_manual(
  name = "Dose",
  values = custom_colors_named
  ) +
  scale_shape_manual(
  name = "Sex",
  values = shape_map
  ) +
  theme_minimal() +
 coord_cartesian(ylim = c(0, 12.5)) +  
  theme(
      text = element_text(family = "Arial", size = 12),
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "b",
      panel.grid.major = element_line(size = 0.5),
      panel.grid.minor = element_blank())
print(p)
ggsave(filename = "../plots/pfoa_clerance.png", plot = p, width = 6, height = 3, dpi = 300,bg = "white")



mean <- clearance_fecal %>%
  ungroup() %>%
  summarise(
    n = n(),
    mean_CL_ml_day_kg = mean(CL_ml_day_kg, na.rm = TRUE)
  )

FC <- clearance/mean$mean_CL_ml_day_kg

replicate_summary <- clearance_fecal%>%
  group_by(Dose, Time) %>%  
  summarise(n = n(), .groups = "drop")
min_n <- min(replicate_summary$n)
max_n <- max(replicate_summary$n)
cat(sprintf("n = %d–%d mice/group\n", min_n, max_n))
```






#Human equvilant dose using httk 2.7.2
#CHMS
```{r}
#load in total data in ng/ml 2018-19, total, 3-79
chms <- data.frame(
  Compound = c("PFOS", "PFOA"),
  GeometricMean = c(2.5, 1.2 ),
  CI_Lower = c(2.3, 1.1),
  CI_Upper = c(2.8, 1.3)
)

chms <- chms %>%
  mutate(
    # ng/mL → mg/L
    C_plasma_mg_L = GeometricMean * 1e-3,

    CL_L_kg_day = case_when(
      #pfas.clearance httk function imported as L/H/KG times by 24 
      Compound == "PFOS" ~ 4.7355e-06 *24	, 
      Compound == "PFOA" ~ 5.5615e-06*24
    ),

    Intake_mg_kg_day = C_plasma_mg_L * CL_L_kg_day,

    Intake_low = CI_Lower * 1e-3 * CL_L_kg_day,
    Intake_high = CI_Upper * 1e-3 * CL_L_kg_day
  )

#https://pmc.ncbi.nlm.nih.gov/articles/PMC1964923/
#imported as ng/ml  arithmetric mean 
firefighters <- data.frame(
  Compound = c("PFOS", "PFOA"),
  GeometricMean = c(799, 691),
  CI_Lower = c(145, 72),
  CI_Upper = c(3490, 5200)
)
firefighters <- firefighters %>%
  mutate(
    # ng/mL → mg/L
    C_plasma_mg_L = GeometricMean * 1e-3,

    CL_L_kg_day = case_when(
        Compound == "PFOS" ~ 4.7355e-06 *24	, 
      Compound == "PFOA" ~ 5.5615e-06*24
    ),

    Intake_mg_kg_day = C_plasma_mg_L * CL_L_kg_day,

    Intake_low = CI_Lower * 1e-3 * CL_L_kg_day,
    Intake_high = CI_Upper * 1e-3 * CL_L_kg_day
  )
combined <- rbind(firefighters, chms)
```

##PFOS Oral equiv
```{r}

shape_map <- c(`Male` = 24, `Female` = 21)
custom_colors_named <- c(
  "0"   = "#330597",
  "0.166"   = "#b12a90",
  "0.5"     = "#d35171",
  "1"       = "#f68f44",
  "1.5"     = "#fec029")


pfos_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOS") %>%
  mutate(uM = as.numeric(trimws(uM)))

#I am using averaged PFAS conc in the plasma per dose and time group
plasma_obs <- pfos_obs %>%
  filter(Tissue == "Plasma") %>%
  select(Dose, Time, uM)
plasma_obs_avg_uM <- plasma_obs %>%
  group_by(Dose, Time) %>%
  summarise(avg_uM = mean(uM, na.rm = TRUE))

dose_vec <- unique(plasma_obs_avg_uM$avg_uM)

oral_equiv_results <- plasma_obs_avg_uM %>%
  rowwise() %>%
  mutate(
    # Get human PFOS PK parameters (1-compartment PFAS model)
    pars = list(parameterize_pfas1comp(
      chem.cas = "1763-23-1",
      species = "Human",
      dosingadj = "Oral"
    )),

      pars = list({pars$Clint <- 0;   #https://pmc.ncbi.nlm.nih.gov/articles/PMC11435625/#sec3-toxics-12-00672
      pars$Rblood2plasma <- 0.588; #httk 
      pars$Vdist <- 0.23		#httk load pfas
      pars$Funbound.plasma <-  0.000753; # file:///C:/Users/aloan/Downloads/toxics-12-00253.pdf
      pars$Caco2.Pab <- 1.6; #httk default with function
      pars$kelim <- 2.059e-05; pars}), # httk load pfas
    view(pars),
    write.csv(pars, "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/PBTK-Modelling-PFAS/Output/pars_pfos_hed.csv"),
    oral_equiv_mgkgd = calc_mc_oral_equiv(
      species = "Human",
      chem.cas = "1763-23-1",
      conc = avg_uM,
      model = "pfas1compartment",
      input.units = "uM",
      output.units = "mgpkgpday",
      samples = 2000,
      parameters = pars
    )
  ) %>%
  ungroup() %>%
  select(Dose, Time, avg_uM, oral_equiv_mgkgd)



pfos_biodata <- combined %>%
  filter(Compound == "PFOS") 

oral_equiv_results$Dose_Time <- paste0(oral_equiv_results$Dose, " (", oral_equiv_results$Time, ")")

p <- ggplot() +
  # Points: colored by Dose
  geom_point(
    data = oral_equiv_results, 
    aes(
      x = factor(Dose_Time),
      y = oral_equiv_mgkgd,
      color = factor(Dose),
      fill  = factor(Dose),
    ), alpha = 0.6, size = 3, stroke = 1
  ) +
geom_hline(
  data = pfos_biodata,
  aes(yintercept = Intake_mg_kg_day),
  color = c("red", "blue"),
  linetype = "dashed",
  linewidth = 0.8
)+
  # Horizontal lines: colored by Source
geom_rect(
  data = pfos_biodata,
  aes(
    ymin = Intake_low,
    ymax = Intake_high
  ),
  xmin = -Inf,
  xmax = Inf,
  fill = c("red", "blue"),
  alpha = 0.4
) +
  # Log10 y-axis
 scale_y_log10(
  limits = c(1e-7, 1e-1),
  breaks = c(1e-6, 1e-5, 1e-4, 1e-3, 1e-2)
) +
  # Point colors for Dose
  scale_color_manual(
    name   = "Dose (mg/kg/day)",
    values = custom_colors_named
  ) +
  scale_fill_manual(
  name = "Dose",
  values = custom_colors_named
  ) +
  labs(
    title = "Predicted vs Observed PFOS",
    x = "Dose (mg/kg/day)",
    y = "mg/kg/day"
  ) +

  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none",
    panel.grid.major = element_line(linewidth = 0.4),
    panel.grid.minor = element_blank()
  )

print(p)

ggsave(filename = "../plots/pfos_hed.png", plot = p, width = 9, height = 3, dpi = 300,bg = "white")
```


##PFOA Oral equiv
```{r}

pfoa_obs <- pfas_obs_all %>%
  filter(PFAS_type == "PFOA") %>%
  mutate(uM = as.numeric(trimws(uM)))

#I am using averaged PFAS conc in the plasma per dose and time group
plasma_obs <- pfoa_obs %>%
  filter(Tissue == "Plasma") %>%
  select(Dose, Time, uM)
plasma_obs_avg_uM <- plasma_obs %>%
  group_by(Dose, Time) %>%
  summarise(avg_uM = mean(uM, na.rm = TRUE))

dose_vec <- unique(plasma_obs_avg_uM$avg_uM)

oral_equiv_results <- plasma_obs_avg_uM %>%
  rowwise() %>%
  mutate(
    # Get human PFOA PK parameters (1-compartment PFAS model)
    pars = list(parameterize_pfas1comp(
      chem.cas = "335-67-1",
      species = "Human",
      dosingadj = "Oral",
      suppress.messages = TRUE
    )),
    view(pars),
      pars = list({pars$Clint <- 0;   #https://pmc.ncbi.nlm.nih.gov/articles/PMC11435625/#sec3-toxics-12-00672
      pars$Rblood2plasma <- 0.9047; #httk 
      pars$Vdist <- 0.17	#httk load pfas
      pars$Caco2.Pab <- 1.6; #httk default with function
      pars$Funbound.plasma <- 0.00245;   # file:///C:/Users/aloan/Downloads/toxics-12-00253.pdf
      pars$kelim <- 3.2715e-05 ; pars}), #httk load pfas
    
      view(pars),
    write.csv(pars, "C:/Users/aloan/OneDrive - HC-SC PHAC-ASPC/Documents/PBTK-Modelling-PFAS/Output/pars_pfoa_hed.csv"),
    # Calculate human oral equivalent dose
    oral_equiv_mgkgd = calc_mc_oral_equiv(
      species = "Human",
      chem.cas = "1763-23-1",
      conc = avg_uM,
      model = "pfas1compartment",
      input.units = "uM",
      output.units = "mgpkgpday",
      samples = 2000,
      parameters = pars
    )
  ) %>%
  ungroup() %>%
  select(Dose, Time, avg_uM, oral_equiv_mgkgd)


oral_equiv_results

pfoa_biodata <- combined %>%
  filter(Compound == "PFOA" ) 

oral_equiv_results$Dose_Time <- paste0(oral_equiv_results$Dose, " (", oral_equiv_results$Time, ")")

p <- ggplot() +
  # Points: colored by Dose
  geom_point(
    data = oral_equiv_results, 
    aes(
      x = factor(Dose_Time),
      y = oral_equiv_mgkgd,
      color = factor(Dose),
      fill  = factor(Dose),
    ), alpha = 0.6, size = 3, stroke = 1
  ) +
geom_hline(
  data = pfoa_biodata,
  aes(yintercept = Intake_mg_kg_day),
  color = c("red", "blue"),
  linetype = "dashed",
  linewidth = 0.8
)+
  # Horizontal lines: colored by Source
geom_rect(
  data = pfoa_biodata,
  aes(
    ymin = Intake_low,
    ymax = Intake_high
  ),
  xmin = -Inf,
  xmax = Inf,
  fill = c("red", "blue"),
  alpha = 0.4
) +
  # Log10 y-axis
 scale_y_log10(
  limits = c(1e-7, 1e-1),
  breaks = c(1e-6, 1e-5, 1e-4, 1e-3, 1e-2)
) +

  # Point colors for Dose
  scale_color_manual(
    name   = "Dose (mg/kg/day)",
    values = custom_colors_named
  ) +
  scale_fill_manual(
  name = "Dose",
  values = custom_colors_named
  ) +
  labs(
    title = "Predicted vs Observed PFOA",
    x = "Dose (mg/kg/day)",
    y = "mg/kg/day"
  ) +

  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none",
    panel.grid.major = element_line(linewidth = 0.4),
    panel.grid.minor = element_blank()
  )

print(p)
ggsave(filename = "../plots/pfoa_hed.png", plot = p, width = 9, height = 3, dpi = 300,bg = "white")
```



